"""empty message

Revision ID: 1921a517cea8
Revises: cef0507a68fd
Create Date: 2023-04-18 19:32:34.467483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1921a517cea8'
down_revision = 'cef0507a68fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_site1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=True),
    sa.Column('expiration_date', sa.String(length=5), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['site1_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cards_site1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards_site1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('card_number', sa.VARCHAR(length=16), nullable=False),
    sa.Column('expiration_date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('cvv', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['site1_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card_site1')
    # ### end Alembic commands ###
